on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: 'hello_world'

    - name: List build artifacts
      run: |
        ls -l build/

    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test_fw.bin
        path: |
          hello_world/build/test_fw.bin

